export const noteActionTypes = {
  TOGGLE_FORM_HIDDEN: "TOGGLE_FORM_HIDDEN",
  CREATE_NOTE: "CREATE_NOTE",
  SELECT_NOTE: "SELECT_NOTE",
	DELETE_NOTE: "DELETE_NOTE",
	START_EDIT: "START_EDIT",
  EDIT_NOTE: "EDIT_NOTE"
};
